"""Shared configuration defaults for timeouts and quality thresholds."""

# Default request timeout for long-running inference or large payload transfers.
DEFAULT_HTTP_TIMEOUT_S = 300

# Default timeout for subprocesses that may download/load models or run GPU checks.
DEFAULT_PROCESS_TIMEOUT_S = 300

# Default quality thresholds used when configuration files/env overrides are unset.
DEFAULT_COLLISION_FREE_RATE_MIN = 0.90
DEFAULT_QUALITY_SCORE_MIN = 0.92
DEFAULT_AVERAGE_QUALITY_SCORE_MIN = 0.90
DEFAULT_SENSOR_CAPTURE_RATE_MIN = 0.95
DEFAULT_PHYSICS_VALIDATION_RATE_MIN = 0.95
DEFAULT_INVENTORY_MIN_OBJECTS = 1
DEFAULT_VARIATION_MIN_OBJECTS = 1
DEFAULT_VARIATION_3D_SUCCESS_RATE_MIN = 0.50
DEFAULT_SCALE_FACTOR_MIN = 0.50
DEFAULT_SCALE_FACTOR_MAX = 2.00
DEFAULT_SCALE_CONFIDENCE_MIN = 0.50
DEFAULT_INTERACTIVE_OK_RATE_MIN = 0.50
DEFAULT_INTERACTIVE_STABILITY_RATE_MIN = 0.90
DEFAULT_INTERACTIVE_FALLBACK_RATE_MAX = 0.50
