# Log-based metric: blueprint_job_timeout_usage_ratio
name: blueprint_job_timeout_usage_ratio
description: "Ratio of execution duration to configured timeout per job invocation."
filter: >
  resource.type="workflows.googleapis.com/Workflow" AND
  jsonPayload.bp_metric="job_invocation" AND
  jsonPayload.event="complete"
metricDescriptor:
  metricKind: GAUGE
  valueType: DOUBLE
  unit: "1"
valueExtractor: EXTRACT(jsonPayload.timeout_usage_ratio)
labelExtractors:
  workflow: EXTRACT(jsonPayload.workflow)
  job: EXTRACT(jsonPayload.job)
  scene_id: EXTRACT(jsonPayload.scene_id)
