# Log-based metric: blueprint_job_retry_exhausted_total
name: blueprint_job_retry_exhausted_total
description: "Count of workflow job starts that exhausted retries."
filter: >
  resource.type="workflows.googleapis.com/Workflow" AND
  jsonPayload.bp_metric="job_retry_exhausted"
metricDescriptor:
  metricKind: DELTA
  valueType: INT64
  unit: "1"
labelExtractors:
  workflow: EXTRACT(jsonPayload.workflow)
  job: EXTRACT(jsonPayload.job)
  scene_id: EXTRACT(jsonPayload.scene_id)
