# Log-based metric: blueprint_job_failure_events
name: blueprint_job_failure_events
description: "Count of workflow job invocations that completed with FAILED status."
filter: >
  resource.type="workflows.googleapis.com/Workflow" AND
  jsonPayload.bp_metric="job_invocation" AND
  jsonPayload.event="complete" AND
  jsonPayload.status="FAILED"
metricDescriptor:
  metricKind: DELTA
  valueType: INT64
  unit: "1"
labelExtractors:
  workflow: EXTRACT(jsonPayload.workflow)
  job: EXTRACT(jsonPayload.job)
  scene_id: EXTRACT(jsonPayload.scene_id)
