#!/bin/bash
# =============================================================================
# Setup EventArc trigger for source-orchestrator (text-first scene requests)
# =============================================================================
#
# Usage:
#   ./setup-source-orchestrator-trigger.sh <project_id> <bucket_name> [workflow_region] [image_path_mode] [text_gen_runtime]
#
# Trigger target:
#   scenes/{scene_id}/prompts/scene_request.json
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_ID=${1:-$(gcloud config get-value project)}
BUCKET=${2:-"${PROJECT_ID}-blueprint-scenes"}
WORKFLOW_REGION=${3:-"us-central1"}
IMAGE_PATH_MODE=${4:-${IMAGE_PATH_MODE:-"orchestrator"}}
TEXT_GEN_RUNTIME=${5:-${TEXT_GEN_RUNTIME:-"vm"}}
TEXT_SCENE_GEN_JOB_NAME=${TEXT_SCENE_GEN_JOB_NAME:-"text-scene-gen-job"}
TEXT_SCENE_ADAPTER_JOB_NAME=${TEXT_SCENE_ADAPTER_JOB_NAME:-"text-scene-adapter-job"}
DEFAULT_SOURCE_MODE=${DEFAULT_SOURCE_MODE:-"text"}
TEXT_BACKEND_DEFAULT=${TEXT_BACKEND_DEFAULT:-"sage"}
TEXT_BACKEND_ALLOWLIST=${TEXT_BACKEND_ALLOWLIST:-"internal,scenesmith,sage,hybrid_serial"}
TEXT_GEN_STANDARD_PROFILE=${TEXT_GEN_STANDARD_PROFILE:-"standard_v1"}
TEXT_GEN_PREMIUM_PROFILE=${TEXT_GEN_PREMIUM_PROFILE:-"premium_v1"}
TEXT_GEN_USE_LLM=${TEXT_GEN_USE_LLM:-"true"}
TEXT_GEN_LLM_MAX_ATTEMPTS=${TEXT_GEN_LLM_MAX_ATTEMPTS:-"3"}
TEXT_GEN_LLM_RETRY_BACKOFF_SECONDS=${TEXT_GEN_LLM_RETRY_BACKOFF_SECONDS:-"2"}
TEXT_ASSET_RETRIEVAL_ENABLED=${TEXT_ASSET_RETRIEVAL_ENABLED:-"true"}
TEXT_ASSET_LIBRARY_PREFIXES=${TEXT_ASSET_LIBRARY_PREFIXES:-"scenes"}
TEXT_ASSET_LIBRARY_MAX_FILES=${TEXT_ASSET_LIBRARY_MAX_FILES:-"2500"}
TEXT_ASSET_LIBRARY_MIN_SCORE=${TEXT_ASSET_LIBRARY_MIN_SCORE:-"0.25"}
TEXT_ASSET_RETRIEVAL_MODE=${TEXT_ASSET_RETRIEVAL_MODE:-"ann_shadow"}
TEXT_ASSET_ANN_ENABLED=${TEXT_ASSET_ANN_ENABLED:-"true"}
TEXT_ASSET_ANN_TOP_K=${TEXT_ASSET_ANN_TOP_K:-"40"}
TEXT_ASSET_ANN_MIN_SCORE=${TEXT_ASSET_ANN_MIN_SCORE:-"0.28"}
TEXT_ASSET_ANN_MAX_RERANK=${TEXT_ASSET_ANN_MAX_RERANK:-"20"}
TEXT_ASSET_ANN_NAMESPACE=${TEXT_ASSET_ANN_NAMESPACE:-"assets-v1"}
TEXT_ASSET_LEXICAL_FALLBACK_ENABLED=${TEXT_ASSET_LEXICAL_FALLBACK_ENABLED:-"true"}
TEXT_ASSET_ROLLOUT_STATE_PREFIX=${TEXT_ASSET_ROLLOUT_STATE_PREFIX:-"automation/asset_retrieval_rollout"}
TEXT_ASSET_ROLLOUT_MIN_DECISIONS=${TEXT_ASSET_ROLLOUT_MIN_DECISIONS:-"500"}
TEXT_ASSET_ROLLOUT_MIN_HIT_RATE=${TEXT_ASSET_ROLLOUT_MIN_HIT_RATE:-"0.95"}
TEXT_ASSET_ROLLOUT_MAX_ERROR_RATE=${TEXT_ASSET_ROLLOUT_MAX_ERROR_RATE:-"0.01"}
TEXT_ASSET_ROLLOUT_MAX_P95_MS=${TEXT_ASSET_ROLLOUT_MAX_P95_MS:-"400"}
TEXT_ASSET_EMBEDDING_QUEUE_PREFIX=${TEXT_ASSET_EMBEDDING_QUEUE_PREFIX:-"automation/asset_embedding/queue"}
TEXT_ASSET_EMBEDDING_PROCESSED_PREFIX=${TEXT_ASSET_EMBEDDING_PROCESSED_PREFIX:-"automation/asset_embedding/processed"}
TEXT_ASSET_EMBEDDING_FAILED_PREFIX=${TEXT_ASSET_EMBEDDING_FAILED_PREFIX:-"automation/asset_embedding/failed"}
TEXT_ASSET_EMBEDDING_MODEL=${TEXT_ASSET_EMBEDDING_MODEL:-"text-embedding-3-small"}
VECTOR_STORE_PROVIDER=${VECTOR_STORE_PROVIDER:-"vertex"}
VECTOR_STORE_PROJECT_ID=${VECTOR_STORE_PROJECT_ID:-"${PROJECT_ID}"}
VECTOR_STORE_LOCATION=${VECTOR_STORE_LOCATION:-"${WORKFLOW_REGION}"}
VECTOR_STORE_NAMESPACE=${VECTOR_STORE_NAMESPACE:-"assets-v1"}
VECTOR_STORE_DIMENSION=${VECTOR_STORE_DIMENSION:-"1536"}
VERTEX_INDEX_ENDPOINT=${VERTEX_INDEX_ENDPOINT:-""}
VERTEX_DEPLOYED_INDEX_ID=${VERTEX_DEPLOYED_INDEX_ID:-""}
TEXT_ASSET_CATALOG_ENABLED=${TEXT_ASSET_CATALOG_ENABLED:-"true"}
TEXT_ASSET_REPLICATION_ENABLED=${TEXT_ASSET_REPLICATION_ENABLED:-"true"}
TEXT_ASSET_REPLICATION_QUEUE_PREFIX=${TEXT_ASSET_REPLICATION_QUEUE_PREFIX:-"automation/asset_replication/queue"}
TEXT_ASSET_REPLICATION_TARGET=${TEXT_ASSET_REPLICATION_TARGET:-"backblaze_b2"}
TEXT_ASSET_REPLICATION_TARGET_PREFIX=${TEXT_ASSET_REPLICATION_TARGET_PREFIX:-"assets"}
TEXT_ASSET_GENERATION_ENABLED=${TEXT_ASSET_GENERATION_ENABLED:-"true"}
TEXT_ASSET_GENERATION_PROVIDER=${TEXT_ASSET_GENERATION_PROVIDER:-"sam3d"}
TEXT_ASSET_GENERATION_PROVIDER_CHAIN=${TEXT_ASSET_GENERATION_PROVIDER_CHAIN:-"sam3d,hunyuan3d"}
TEXT_ASSET_GENERATED_CACHE_ENABLED=${TEXT_ASSET_GENERATED_CACHE_ENABLED:-"true"}
TEXT_ASSET_GENERATED_CACHE_PREFIX=${TEXT_ASSET_GENERATED_CACHE_PREFIX:-"asset-library/generated-text"}
TEXT_SAM3D_API_HOST=${TEXT_SAM3D_API_HOST:-""}
TEXT_SAM3D_TEXT_ENDPOINTS=${TEXT_SAM3D_TEXT_ENDPOINTS:-"/openapi/v1/text-to-3d,/v1/text-to-3d"}
TEXT_SAM3D_TIMEOUT_SECONDS=${TEXT_SAM3D_TIMEOUT_SECONDS:-"1800"}
TEXT_SAM3D_POLL_SECONDS=${TEXT_SAM3D_POLL_SECONDS:-"10"}
TEXT_HUNYUAN_API_HOST=${TEXT_HUNYUAN_API_HOST:-""}
TEXT_HUNYUAN_TEXT_ENDPOINTS=${TEXT_HUNYUAN_TEXT_ENDPOINTS:-"/openapi/v1/text-to-3d,/v1/text-to-3d"}
TEXT_HUNYUAN_TIMEOUT_SECONDS=${TEXT_HUNYUAN_TIMEOUT_SECONDS:-"1800"}
TEXT_HUNYUAN_POLL_SECONDS=${TEXT_HUNYUAN_POLL_SECONDS:-"10"}
TEXT_GEN_MAX_SEEDS=${TEXT_GEN_MAX_SEEDS:-"16"}
TEXT_GEN_ENABLE_IMAGE_FALLBACK=${TEXT_GEN_ENABLE_IMAGE_FALLBACK:-"true"}
ARENA_EXPORT_REQUIRED=${ARENA_EXPORT_REQUIRED:-"true"}
IMAGE_ORCHESTRATOR_WORKFLOW_NAME=${IMAGE_ORCHESTRATOR_WORKFLOW_NAME:-"image-to-scene-orchestrator"}
IMAGE_LEGACY_WORKFLOW_NAME=${IMAGE_LEGACY_WORKFLOW_NAME:-"image-to-scene-pipeline"}
IMAGE_LEGACY_CHAIN_WAIT_SECONDS=${IMAGE_LEGACY_CHAIN_WAIT_SECONDS:-"7200"}
TEXT_GEN_VM_NAME=${TEXT_GEN_VM_NAME:-"isaac-sim-ubuntu"}
TEXT_GEN_VM_ZONE=${TEXT_GEN_VM_ZONE:-"us-east1-c"}
TEXT_GEN_VM_REPO_DIR=${TEXT_GEN_VM_REPO_DIR:-"~/BlueprintPipeline"}
TEXT_GEN_VM_TIMEOUT_SECONDS=${TEXT_GEN_VM_TIMEOUT_SECONDS:-"2400"}
SAGE_RUNTIME_MODE=${SAGE_RUNTIME_MODE:-"cloudrun"}
SAGE_SERVER_URL=${SAGE_SERVER_URL:-""}
SAGE_TIMEOUT_SECONDS=${SAGE_TIMEOUT_SECONDS:-"900"}
SCENESMITH_RUNTIME_MODE=${SCENESMITH_RUNTIME_MODE:-"cloudrun"}
SCENESMITH_SERVER_URL=${SCENESMITH_SERVER_URL:-""}
SCENESMITH_TIMEOUT_SECONDS=${SCENESMITH_TIMEOUT_SECONDS:-"1800"}
TEXT_SAGE_ACTION_DEMO_ENABLED=${TEXT_SAGE_ACTION_DEMO_ENABLED:-"false"}

# Eventarc trigger location must match bucket location (appspot buckets are multi-region "US")
TRIGGER_LOCATION="us"

TRIGGER_NAME="scene-request-source-orchestrator-trigger"
WORKFLOW_NAME="source-orchestrator"
WORKFLOW_SA="workflow-invoker"

echo -e "${GREEN}=== Source Orchestrator Trigger Setup ===${NC}"
echo "Project:           ${PROJECT_ID}"
echo "Bucket:            ${BUCKET}"
echo "Trigger location:  ${TRIGGER_LOCATION}"
echo "Workflow region:   ${WORKFLOW_REGION}"
echo "Image path mode:   ${IMAGE_PATH_MODE}"
echo "Text runtime:      ${TEXT_GEN_RUNTIME}"
echo "Text backend:      ${TEXT_BACKEND_DEFAULT}"
echo ""

echo -e "${BLUE}Step 1: Enabling required APIs...${NC}"
gcloud services enable \
    eventarc.googleapis.com \
    workflows.googleapis.com \
    workflowexecutions.googleapis.com \
    cloudbuild.googleapis.com \
    run.googleapis.com \
    storage.googleapis.com \
    compute.googleapis.com \
    --project=${PROJECT_ID}
echo -e "${GREEN}APIs enabled${NC}"
echo ""

echo -e "${BLUE}Step 2: Setting up service account...${NC}"
SA_EMAIL="${WORKFLOW_SA}@${PROJECT_ID}.iam.gserviceaccount.com"
PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)')"
CLOUD_BUILD_SA="${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com"

if ! gcloud iam service-accounts describe ${SA_EMAIL} --project=${PROJECT_ID} 2>/dev/null; then
    echo -e "${YELLOW}Creating service account ${WORKFLOW_SA}...${NC}"
    gcloud iam service-accounts create ${WORKFLOW_SA} \
        --display-name="Workflow Invoker SA" \
        --project=${PROJECT_ID}
    sleep 5
else
    echo "Service account ${WORKFLOW_SA} already exists"
fi

echo "Granting permissions..."
for ROLE in \
    "roles/workflows.invoker" \
    "roles/run.invoker" \
    "roles/storage.objectAdmin" \
    "roles/logging.logWriter" \
    "roles/compute.instanceAdmin.v1" \
    "roles/cloudbuild.builds.editor" \
    "roles/eventarc.eventReceiver"; do
    gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member="serviceAccount:${SA_EMAIL}" \
        --role="${ROLE}" \
        --quiet 2>&1 | tail -1
done

for ROLE in \
    "roles/compute.instanceAdmin.v1" \
    "roles/compute.osAdminLogin" \
    "roles/logging.logWriter"; do
    gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member="serviceAccount:${CLOUD_BUILD_SA}" \
        --role="${ROLE}" \
        --quiet 2>&1 | tail -1
done

GCS_SA="service-${PROJECT_NUMBER}@gs-project-accounts.iam.gserviceaccount.com"
gcloud projects add-iam-policy-binding ${PROJECT_ID} \
    --member="serviceAccount:${GCS_SA}" \
    --role="roles/pubsub.publisher" \
    --quiet 2>&1 | tail -1

echo -e "${GREEN}Permissions granted${NC}"
echo ""

echo -e "${BLUE}Step 3: Deploying source orchestrator workflow...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
gcloud workflows deploy ${WORKFLOW_NAME} \
    --location=${WORKFLOW_REGION} \
    --source="${SCRIPT_DIR}/source-orchestrator.yaml" \
    --set-env-vars="DEFAULT_SOURCE_MODE=${DEFAULT_SOURCE_MODE},TEXT_BACKEND_DEFAULT=${TEXT_BACKEND_DEFAULT},TEXT_BACKEND_ALLOWLIST=${TEXT_BACKEND_ALLOWLIST},TEXT_GEN_RUNTIME=${TEXT_GEN_RUNTIME},TEXT_SCENE_GEN_JOB_NAME=${TEXT_SCENE_GEN_JOB_NAME},TEXT_SCENE_ADAPTER_JOB_NAME=${TEXT_SCENE_ADAPTER_JOB_NAME},TEXT_GEN_STANDARD_PROFILE=${TEXT_GEN_STANDARD_PROFILE},TEXT_GEN_PREMIUM_PROFILE=${TEXT_GEN_PREMIUM_PROFILE},TEXT_GEN_USE_LLM=${TEXT_GEN_USE_LLM},TEXT_GEN_LLM_MAX_ATTEMPTS=${TEXT_GEN_LLM_MAX_ATTEMPTS},TEXT_GEN_LLM_RETRY_BACKOFF_SECONDS=${TEXT_GEN_LLM_RETRY_BACKOFF_SECONDS},TEXT_ASSET_RETRIEVAL_ENABLED=${TEXT_ASSET_RETRIEVAL_ENABLED},TEXT_ASSET_LIBRARY_PREFIXES=${TEXT_ASSET_LIBRARY_PREFIXES},TEXT_ASSET_LIBRARY_MAX_FILES=${TEXT_ASSET_LIBRARY_MAX_FILES},TEXT_ASSET_LIBRARY_MIN_SCORE=${TEXT_ASSET_LIBRARY_MIN_SCORE},TEXT_ASSET_RETRIEVAL_MODE=${TEXT_ASSET_RETRIEVAL_MODE},TEXT_ASSET_ANN_ENABLED=${TEXT_ASSET_ANN_ENABLED},TEXT_ASSET_ANN_TOP_K=${TEXT_ASSET_ANN_TOP_K},TEXT_ASSET_ANN_MIN_SCORE=${TEXT_ASSET_ANN_MIN_SCORE},TEXT_ASSET_ANN_MAX_RERANK=${TEXT_ASSET_ANN_MAX_RERANK},TEXT_ASSET_ANN_NAMESPACE=${TEXT_ASSET_ANN_NAMESPACE},TEXT_ASSET_LEXICAL_FALLBACK_ENABLED=${TEXT_ASSET_LEXICAL_FALLBACK_ENABLED},TEXT_ASSET_ROLLOUT_STATE_PREFIX=${TEXT_ASSET_ROLLOUT_STATE_PREFIX},TEXT_ASSET_ROLLOUT_MIN_DECISIONS=${TEXT_ASSET_ROLLOUT_MIN_DECISIONS},TEXT_ASSET_ROLLOUT_MIN_HIT_RATE=${TEXT_ASSET_ROLLOUT_MIN_HIT_RATE},TEXT_ASSET_ROLLOUT_MAX_ERROR_RATE=${TEXT_ASSET_ROLLOUT_MAX_ERROR_RATE},TEXT_ASSET_ROLLOUT_MAX_P95_MS=${TEXT_ASSET_ROLLOUT_MAX_P95_MS},TEXT_ASSET_EMBEDDING_QUEUE_PREFIX=${TEXT_ASSET_EMBEDDING_QUEUE_PREFIX},TEXT_ASSET_EMBEDDING_PROCESSED_PREFIX=${TEXT_ASSET_EMBEDDING_PROCESSED_PREFIX},TEXT_ASSET_EMBEDDING_FAILED_PREFIX=${TEXT_ASSET_EMBEDDING_FAILED_PREFIX},TEXT_ASSET_EMBEDDING_MODEL=${TEXT_ASSET_EMBEDDING_MODEL},VECTOR_STORE_PROVIDER=${VECTOR_STORE_PROVIDER},VECTOR_STORE_PROJECT_ID=${VECTOR_STORE_PROJECT_ID},VECTOR_STORE_LOCATION=${VECTOR_STORE_LOCATION},VECTOR_STORE_NAMESPACE=${VECTOR_STORE_NAMESPACE},VECTOR_STORE_DIMENSION=${VECTOR_STORE_DIMENSION},VERTEX_INDEX_ENDPOINT=${VERTEX_INDEX_ENDPOINT},VERTEX_DEPLOYED_INDEX_ID=${VERTEX_DEPLOYED_INDEX_ID},TEXT_ASSET_CATALOG_ENABLED=${TEXT_ASSET_CATALOG_ENABLED},TEXT_ASSET_REPLICATION_ENABLED=${TEXT_ASSET_REPLICATION_ENABLED},TEXT_ASSET_REPLICATION_QUEUE_PREFIX=${TEXT_ASSET_REPLICATION_QUEUE_PREFIX},TEXT_ASSET_REPLICATION_TARGET=${TEXT_ASSET_REPLICATION_TARGET},TEXT_ASSET_REPLICATION_TARGET_PREFIX=${TEXT_ASSET_REPLICATION_TARGET_PREFIX},TEXT_ASSET_GENERATION_ENABLED=${TEXT_ASSET_GENERATION_ENABLED},TEXT_ASSET_GENERATION_PROVIDER=${TEXT_ASSET_GENERATION_PROVIDER},TEXT_ASSET_GENERATION_PROVIDER_CHAIN=${TEXT_ASSET_GENERATION_PROVIDER_CHAIN},TEXT_ASSET_GENERATED_CACHE_ENABLED=${TEXT_ASSET_GENERATED_CACHE_ENABLED},TEXT_ASSET_GENERATED_CACHE_PREFIX=${TEXT_ASSET_GENERATED_CACHE_PREFIX},TEXT_SAM3D_API_HOST=${TEXT_SAM3D_API_HOST},TEXT_SAM3D_TEXT_ENDPOINTS=${TEXT_SAM3D_TEXT_ENDPOINTS},TEXT_SAM3D_TIMEOUT_SECONDS=${TEXT_SAM3D_TIMEOUT_SECONDS},TEXT_SAM3D_POLL_SECONDS=${TEXT_SAM3D_POLL_SECONDS},TEXT_HUNYUAN_API_HOST=${TEXT_HUNYUAN_API_HOST},TEXT_HUNYUAN_TEXT_ENDPOINTS=${TEXT_HUNYUAN_TEXT_ENDPOINTS},TEXT_HUNYUAN_TIMEOUT_SECONDS=${TEXT_HUNYUAN_TIMEOUT_SECONDS},TEXT_HUNYUAN_POLL_SECONDS=${TEXT_HUNYUAN_POLL_SECONDS},TEXT_GEN_MAX_SEEDS=${TEXT_GEN_MAX_SEEDS},TEXT_GEN_ENABLE_IMAGE_FALLBACK=${TEXT_GEN_ENABLE_IMAGE_FALLBACK},ARENA_EXPORT_REQUIRED=${ARENA_EXPORT_REQUIRED},IMAGE_PATH_MODE=${IMAGE_PATH_MODE},IMAGE_ORCHESTRATOR_WORKFLOW_NAME=${IMAGE_ORCHESTRATOR_WORKFLOW_NAME},IMAGE_LEGACY_WORKFLOW_NAME=${IMAGE_LEGACY_WORKFLOW_NAME},IMAGE_LEGACY_CHAIN_WAIT_SECONDS=${IMAGE_LEGACY_CHAIN_WAIT_SECONDS},TEXT_GEN_VM_NAME=${TEXT_GEN_VM_NAME},TEXT_GEN_VM_ZONE=${TEXT_GEN_VM_ZONE},TEXT_GEN_VM_REPO_DIR=${TEXT_GEN_VM_REPO_DIR},TEXT_GEN_VM_TIMEOUT_SECONDS=${TEXT_GEN_VM_TIMEOUT_SECONDS},SAGE_RUNTIME_MODE=${SAGE_RUNTIME_MODE},SAGE_SERVER_URL=${SAGE_SERVER_URL},SAGE_TIMEOUT_SECONDS=${SAGE_TIMEOUT_SECONDS},SCENESMITH_RUNTIME_MODE=${SCENESMITH_RUNTIME_MODE},SCENESMITH_SERVER_URL=${SCENESMITH_SERVER_URL},SCENESMITH_TIMEOUT_SECONDS=${SCENESMITH_TIMEOUT_SECONDS},TEXT_SAGE_ACTION_DEMO_ENABLED=${TEXT_SAGE_ACTION_DEMO_ENABLED}" \
    --service-account=${SA_EMAIL} \
    --project=${PROJECT_ID}
echo -e "${GREEN}Workflow deployed${NC}"
echo ""

echo -e "${BLUE}Step 4: Recreating trigger if needed...${NC}"
if gcloud eventarc triggers describe ${TRIGGER_NAME} --location=${TRIGGER_LOCATION} --project=${PROJECT_ID} 2>/dev/null; then
    echo -e "${YELLOW}Trigger ${TRIGGER_NAME} exists; deleting and recreating...${NC}"
    gcloud eventarc triggers delete ${TRIGGER_NAME} \
        --location=${TRIGGER_LOCATION} \
        --project=${PROJECT_ID} \
        --quiet
    sleep 5
fi

echo -e "${BLUE}Step 5: Creating EventArc trigger...${NC}"
gcloud eventarc triggers create ${TRIGGER_NAME} \
    --location=${TRIGGER_LOCATION} \
    --project=${PROJECT_ID} \
    --service-account="${SA_EMAIL}" \
    --destination-workflow=${WORKFLOW_NAME} \
    --destination-workflow-location=${WORKFLOW_REGION} \
    --event-filters="type=google.cloud.storage.object.v1.finalized" \
    --event-filters="bucket=${BUCKET}" \
    --event-data-content-type="application/json"
echo -e "${GREEN}Trigger created${NC}"
echo ""

echo -e "${BLUE}Step 6: Verifying trigger...${NC}"
gcloud eventarc triggers describe ${TRIGGER_NAME} \
    --location=${TRIGGER_LOCATION} \
    --project=${PROJECT_ID} \
    --format="table(displayName, destination.workflow, eventFilters)"
echo ""

echo -e "${GREEN}=== Setup Complete ===${NC}"
echo "Workflow: ${WORKFLOW_NAME}"
echo "Trigger:  ${TRIGGER_NAME}"
echo ""
echo "The workflow triggers on bucket object finalize events and filters internally for:"
echo "  scenes/{scene_id}/prompts/scene_request.json"
echo ""
echo "To test:"
echo "  gsutil cp request.json gs://${BUCKET}/scenes/test_scene/prompts/scene_request.json"
