# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    import logging

    logging.getLogger(__name__).warning(
        "gRPC runtime version %s is lower than generated stub version %s; "
        "continuing with legacy stubs.",
        GRPC_VERSION,
        GRPC_GENERATED_VERSION,
    )
