CHECKSUMS_HMAC_KEY_SECRET_ID = "checksums-hmac-key"
CHECKSUMS_HMAC_KEY_ENV_VAR = "CHECKSUMS_HMAC_KEY"
CHECKSUMS_HMAC_KEY_ID_SECRET_ID = "checksums-hmac-key-id"
CHECKSUMS_HMAC_KEY_ID_ENV_VAR = "CHECKSUMS_HMAC_KEY_ID"
MIN_EPISODES_REQUIRED = 1
