steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/pipeline-jobs/asset-replication-job:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/pipeline-jobs/asset-replication-job:$SHORT_SHA",
      ]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/pipeline-jobs/asset-replication-job:$SHORT_SHA"

